### ISSUE TITLE
Last Category and Startup screen settings in Preferences do not work

### ISSUE THREAD

**Issue by aregaero** [tiberiusteng/financisto1-holo#1]
Whatever I change in those settings, application does not react.
Android 14
App version 2023-12-14

**Reproducing steps (for both):**
1. run app
2. change startup screen to blotter
3. relaunch the app
4. change New transaction screen > Last category to checked
5. Create one transaction with selecting payee and category
6. Create another transaction with selection same payee

**Observed:**
Account screen is opened
When second transaction payee is selected, last category is not autoselected

**Expected:**
Blotter screen should be opened.
Last category should be selected

![Screenshot_20231214-224327](https://github.com/tiberiusteng/financisto1-holo/assets/42356810/fb91b5de-f4be-4526-921f-07c6d5663b50)
![Screenshot_20231214-223729](https://github.com/tiberiusteng/financisto1-holo/assets/42356810/ca6d1fb0-2e22-4a0d-b581-598aee216dda)

**Comment by tiberiusteng** [comment]
Both issue will be fixed in next release, thanks for reporting them.
