### ISSUE TITLE
Settings -> Account list -> Date in account list -> Account creation date - incorrect info shown

### ISSUE THREAD

**Issue by secco-online** [tiberiusteng/financisto1-holo#12]
Hello
The smallest of the smallest things but I bring it to your attention.
By setting Settings -> Account list -> Date in account list -> Account creation date, in the account list I was expecting the moment the account was physically created by me in the application. It was quite odd to see that most of my accounts had a very recent date and few years newer than the first transaction recorded on them. 
I tested it and realised that the date that is displayed is not the account creation date but the last modification date. 
To replicate: hit edit on any account in the account lost screen and then don't modify anything, just press save. The current date will be shown as the account creation date.
I'm attaching 2 screenshots.
Of this info is not available in the data model, maybe would be ok to change the label in setting ftom account creation date to account last modification date.
Greetings 
![Screenshot_20240111-224927](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/5070d317-a55c-4e78-95a7-b082aaa42e8e)
![Screenshot_20240111-224824](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/45a487e3-2902-47d1-ae09-92b39d735459)

**Comment by tiberiusteng** [comment]
There's a creation date field in account but it's indeed updated on every change ... and it has another updated_on but seems not correctly updated. I'll see how to sort them out.

**Comment by secco-online** [comment]
Resolved on the latest release
