### ISSUE TITLE
Pie reports - magnifying glass buttons unreadable 

### ISSUE THREAD

**Issue by secco-online** [tiberiusteng/financisto1-holo#13]
Inside pie reports, all of them are impacted, the buttons to zoom in, zoom out and restore basic zoom are practically unreadable. There are very very small icons on the buttons.
I'm attaching a screenshot as the example. 
It seems that they are not scaled to fill the entire button, just placed as a small image in its top left corner

![Screenshot_20240112-102348](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/1ba676f7-4621-47e7-b6b7-0fe0d5d751f7)

**Comment by tiberiusteng** [comment]
this screen is drawn by achartengine, and it's basically not maintained ...

**Comment by secco-online** [comment]
Clear, no solution here due to an outdated library. Thanks for checking

**Comment by tiberiusteng** [comment]
actually it will be fixed in next release ;)

**Comment by secco-online** [comment]
I thought it was impossible after your first comment but I was wrong :) thanks
