### ISSUE TITLE
Financito icon - support for pixel themed icons

### ISSUE THREAD

**Issue by skibbipl** [tiberiusteng/financisto1-holo#17]
Will it be possible to make financito icon compatible with google pixel launcher themed icons?

**Comment by tiberiusteng** [comment]
I'm not good at drawing ... I'll see if I can get someone's help or draw it myself.

ref: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by skibbipl** [comment]
Hmm, I might try to tinker around with original icon in PS. But I suck at drawing as you ;)
