### ISSUE TITLE
Suggestion on "reports" tab

### ISSUE THREAD

**Issue by VanHate** [tiberiusteng/financisto1-holo#24]
Please add selection list to reports "**by period**"
It is very inconvenient to choose category/payee with arrows

<img src="https://github.com/tiberiusteng/financisto1-holo/assets/82833249/9b6476a9-c332-4249-b0c3-89c28e0f3c8c" width=40% height=40%>

**Comment by tiberiusteng** [comment]
I understand your request but I haven't dig into line chart code yet, so don't expect it would soon be implemented ...

**Comment by tiberiusteng** [comment]
implemented in 2024-02-19 release

**Comment by VanHate** [comment]
Thank you, it was really soon
