### ISSUE TITLE
Time picker shows AM/PM even if system locale uses 24h clock

### ISSUE THREAD

**Issue by skibbipl** [tiberiusteng/financisto1-holo#3]
I switched from regular financito to this version. One of the issues I found is that time picker does not respect system time settings. I do not use AM/PM and prefer to have 24h clock selector.

**Comment by tiberiusteng** [comment]
What's your Android version and locale settings, and in what screen's time picker?

Transaction editing screen's code is already checking system preferences' 12/24 config, and I tested on my phone earlier it do switch to am/pm selector if I changed my time format in system preferences.

https://github.com/tiberiusteng/financisto1-holo/blob/5fafa5beea6159cf68086a9b863165d4adb2de9a/app/src/main/java/tw/tib/financisto/activity/AbstractTransactionActivity.java#L224

**Comment by skibbipl** [comment]
I use latest Android 14 on Pixel 8. And the time picker is on new transaction page. My language is set to polish.

**Comment by tiberiusteng** [comment]
Ahh, I probably know the issue. In the meantime you can go to System Preferences -> Date/Time, turn off "Use Locale Default" and turn on "Use 24h format", and it should show 24h time selector.

The code didn't handle the situation well (use locale default and the default 24h time), I'll try to fix it in next version.

**Comment by skibbipl** [comment]
Yes, I can confirm that disabling Use Locale Default resolves the issue. I can wait for the new version.
