### ISSUE TITLE
Issue with Project filter

### ISSUE THREAD

**Issue by yrjoinc** [tiberiusteng/financisto1-holo#31]
Hi there, there's a problem with Project filter in Accounts or Blotter. I can't select the options by touching the 3 lines like I can do with Payee filter, so I need to write manually the project name.

Please watch the video I have attached.

https://github.com/tiberiusteng/financisto1-holo/assets/1975382/3ad473fa-ec2b-4aad-99e3-0806975e28e3

Thanks

**Comment by tiberiusteng** [comment]
Hi, thanks for reporting it, will be fixed in the next release.

**Comment by yrjoinc** [comment]
Thanks a lot for helping us. Great job bringing back to life Financisto, the best app ever to track the expenses.
