### ISSUE TITLE
Transfers included in reports

### ISSUE THREAD

**Issue by secco-online** [tiberiusteng/financisto1-holo#32]
Hello
Recently I ran into a new issue. I'm quite sure is is a very recent behavioural change. 
The bug is the the transfers between own accounts are included as both income and expense and are totally falsifying the reporting.
To replicate:
1. Go to reports 
2. Open a report by category or by period
3. In the bottom left select to see both incomes and expenses (green and orange icon like in the screenshot attached)
4. You will see that if you transfer eg 100eur from one account to another then you will see that day both income and expense of 100eur. 

Expected behaviour (like in the past) only incoming transactions and real expenses shall be shown without self-transfers.

Let me know if it can be fixed or at least to add an option in settings to change this behaviour

Thanks as always
Greetings
![Screenshot_20240301-071810](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/be6f0bf0-6f0a-4735-86bd-6dc6812fca81)

**Comment by tiberiusteng** [comment]
in the left (blue) funnel button there should be a new "Transfer" option at bottom that can be changed to "Exclude", functionally same as the option previously in preferences.

**Comment by secco-online** [comment]
Wow. Cool..this is the option I was looking for.
Thanks as always
Greetings
