### ISSUE TITLE
Top bar inconsistent behaviour in landscape and portrait modes

### ISSUE THREAD

**Issue by secco-online** [tiberiusteng/financisto1-holo#34]
Hello
Recently I noticed a strange behaviour.
I usually hold my phone in portrait mode and I use it always like this. The top menu this way is always filling in the entire width of the screen, evenly spread (first screenshot).
But there is an interesting behaviour when you start the application directly in landscape mode. The icons even after going back to portrait mode are compressed in the middle of the screen and not spread, just grouped in the middle.
To replicate:
- close entirely the application form the recent
- tilt the phone to landscape
- launch the application
- authencate if necessary with fingerprint 
- the main screen opens with the icons grouped in the center

I hope it can help you figure out what is the issue. I suppose some screen measurement taken in onCreate method of the main activity .
Greetings
![Screenshot_20240303-163336](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/d20bd9ef-6131-4246-96d2-2b1b6bed3c73)
![Screenshot_20240303-163213](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/59735f64-2812-4893-a961-b31f9f5b7a36)

**Comment by tiberiusteng** [comment]
Wow, nice catch, and I reproduced it on my phone. I personally don't enable auto rotation and never use my phone in the landscape orientation so I would never found this ...

**Comment by secco-online** [comment]
Thanks:) I was surprised to see it too. I never start the app like this. It was a coincidence: I had the phone on the bed and I opened the app landscape by "mistake" and then I couldn't make it go back to normal until I killed it :)
Thanks as always for the fixing

**Comment by secco-online** [comment]
Resolved in version 2024-03-11. Thanks
