### ISSUE TITLE
Bug - Scheduled transactions recorded twice 

### ISSUE THREAD

**Issue by secco-online** [tiberiusteng/financisto1-holo#36]
Hello
Every scheduled transaction is generated twice with exactly the same amount, description and time. 
Please fix

**Comment by tiberiusteng** [comment]
https://stackoverflow.com/questions/50999673/workmanager-not-repeating-the-periodicworkrequest

https://i.stack.imgur.com/N6er5.jpg

I'll look into it, but I don't think there's much I can do (at least for now ...)

**Comment by tiberiusteng** [comment]
what's the interval you set for those transactions? are they being created/duplicated immediately after you updated the app?

**Comment by secco-online** [comment]
Hello. The schedule il twice per year (every 6 months) with an occurrence on March 11th. The next one  will be September 11th. I'm attaching a screenshot.
It happend without the update of the application, like during a normal schedule occurrence.
Yesterday afternoon (after I already discovered the duplicate transactions) I updated the application to the latest version (2024-03-11).
Today (march 12th) I have a set of 4 scheduled transactions that will happen in more or less 2 hours. They are also bi-yearly (interval of 6 months) so I'll let you know later what the result today.
![Screenshot_20240312-062256](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/0952800f-0b02-439e-8d40-7415f7eea336)

Let me know if you need more data/screenshots for your investigation

**Comment by tiberiusteng** [comment]
wow, just curious, how many scheduled transactions do you have? I heard that some have more than one screen ...

I currently have 2 known problems on scheduled transactions under investigation:
1. it seems they will get executed whenever the app is upgraded (I have found some solutions to try on this one)
2. the same scheduled transaction sometimes got duplicated execution on the same time (I added various checks and locks on previous versions but somehow it still happening

**Comment by secco-online** [comment]
Yesterday I had in total 3 transactions scheduled:
- one monthly on the 11th day of each month
- 2 biyearly ones (march 11th and September 11th) 
and as the result I found 6 transactions generated in the app. Wrong behaviour

Today I had in total 4 transactions scheduled:
- 4 biyearly ones (march 12th and September 12th) 
and as the result I found 4 transactions generated in the app. Correct behaviour 

Yesterday after already discovering the additional transactions, I updated the application to teh latest version

**Comment by secco-online** [comment]
Hi. I'm closing this one. Weeks passed and I didn't have any problem with the scheduled amounts. So maybe all the work, that you dedicated to this error, helped. In case I see a problem in the future , I'll let you know. Greetings
