### ISSUE TITLE
Account list - hiding last transaction date does not work

### ISSUE THREAD

**Issue by secco-online** [tiberiusteng/financisto1-holo#4]
Hello
It's an old issue, since coming from the old financisto application affecting the account list activity.
There is a setting that can be found in preferences -> account list-> hide last transaction date. The setting does not work even after app restart. In the account list the transaction date is always visible.
Thanks a lot for your time you are dedicating to reviving this project
Let me know if you need more details, like a screenshot or sth
Greetings
Mac

**Comment by tiberiusteng** [comment]
swipe back to launcher isn't enough, you must swipe up the app in task switcher to force restart.

**Comment by secco-online** [comment]
It does not work. Can you check it on you phone? It hasn't been Dowling for 14 years for me so for sure it's not the swipe back/application restart issue. All the forks of the original Financisto are having this problem. I attach a screenshot so you can see which info shall be hidden but it is not 
![Screenshot_20240109-062538](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/27232d93-63c0-4065-a05f-41ad66e1130b)

**Comment by tiberiusteng** [comment]
https://github.com/tiberiusteng/financisto1-holo/commit/6997e0bfadd399bda91064fb0f3c0690b34b8b62
It's been updated with a new choice option, and it's indeed working on my phone.

**Comment by secco-online** [comment]
Works
