### ISSUE TITLE
Exchange rate provider

### ISSUE THREAD

**Issue by ColorfulQuark** [tiberiusteng/financisto1-holo#43]
I just installed the program and imported a backup from financisto+.  I get constant pop-ups "please select an exchange rate service providing historical rates, like ...". I've selected free currency. 

How do I make the pop-ups stop?

EDIT:  I created a free openexchangerates account and that made the popups stop.

**Comment by tiberiusteng** [comment]
(For future users searched this issue)

That mean it doesn't have an exchange rate to calculate the current balance of your foreign currency accounts in your home currency.

You can also manually create exchange rate on an earlier date of the offending transaction (the date can be viewed by clicking the total value with exclamation mark).

 I didn't notice the English toast being cropped, will try to fix it later.
