### ISSUE TITLE
Message in Toast after creating a backup manually

### ISSUE THREAD

**Issue by secco-online** [tiberiusteng/financisto1-holo#6]
Hello
The backup works well besides the message that is showed in the toast afterwards. You shall extract the path of the file and not showing STH like: "content://.... Document list/primary%32....". The old school path/filename would be great. In case of questions, just let me know
Mac

**Comment by tiberiusteng** [comment]
what version have you installed / where do you installed it from? the latest version shouldn't show full path as you described.

**Comment by secco-online** [comment]
The latest version I goind on Google play "2024-01-08 b"

**Comment by tiberiusteng** [comment]
ahh, got it, not all language translations have that parameter showing filename so I didn't notice that. Will be fixed later.

**Comment by secco-online** [comment]
Great! You did a great job in reverse engineering the code. But this stuff happens.
