### ISSUE TITLE
Automatic backup does not work

### ISSUE THREAD

**Issue by secco-online** [tiberiusteng/financisto1-holo#7]
Hello
The automatic backup to the local folder does not work. This is a new issue as on the legacy app it worked well.
I use an Android 14 phone if you need the API level for troubleshooting.
Mac

**Comment by tiberiusteng** [comment]
you have to choose/make a new folder for the app to backup. the action of choosing a folder also grants the app write permission.

**Comment by secco-online** [comment]
Folder chosen. Manual backup works, the scheduler does not work. From API 33 the scheduling of exact alarms need additional permission, maybe this is the issue. (I use android 14, api level 34)

**Comment by tiberiusteng** [comment]
It's already rewritten in WorkManager, and it's expected not to run exactly on time.

I configure daily backup on 06:00 and program the work execution time on next expected run time but I've seen the file generated on 04:45, 05:29, 06:35, 10:19 ...

**Comment by secco-online** [comment]
I've been using the app since yesterday so I'll schedule it at 8:00 and see in few days if backups were created

**Comment by secco-online** [comment]
I've checked it and as described by you the backup is created just at random times. Perfect!
Thanks a lot for your continued efforts. From me you have already got 5 stars on Google play on the day one, because of the proving and reviving of this great app.
Greetings
