### ISSUE TITLE
Budget screen. Overlapping labels of categories with the budget amount 

### ISSUE THREAD

**Issue by secco-online** [tiberiusteng/financisto1-holo#8]
A new issue that was not present in the legacy application.
In gacmse budget has a lot of categories included,  there are overlapping labels of categories with the budget amount.
I'm attaching the screenshot form the legacy application there the labels get truncated and the latest version of Financisto Holo with the overlap.
This makes the budget amongst unreadable 
![Screenshot_20240109-112729](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/ba6bdc66-9dd3-482e-911b-4c0ac756878e)
![Screenshot_20240109-112745](https://github.com/tiberiusteng/financisto1-holo/assets/46870782/54b9eb07-b8c9-46a1-b55c-259faa9f4e35)

**Comment by tiberiusteng** [comment]
got it, will be fixed in next release
